---
- name: Configure Jenkins server with Docker, Ansible, and Jenkins
  hosts: jenkins
  become: true

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Install required base packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
        state: present

    # -------------------------
    # Java (required for Jenkins)
    # -------------------------
    - name: Install Java (OpenJDK 17)
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes

    # -------------------------
    # Docker installation
    # -------------------------
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Compose v2 plugin
      apt:
        name: docker-compose-plugin
        state: present
        update_cache: yes

    # -------------------------
    # Ansible installation
    # -------------------------
    - name: Install Ansible
      apt:
        name: ansible
        state: present
        update_cache: yes

    # -------------------------
    # Jenkins installation
    # -------------------------
    - name: Add Jenkins GPG key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present

    - name: Add Jenkins repository
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: presentte
        update_cache: yes
    
    - name: Add Jenkins user to Docker group
      user:
        name: jenkins
        groups: docker
        append: yes
    
    - name: Restart Jenkins to apply group changes
      service:
        name: jenkins
        state: restarted

    - name: Ensure Jenkins service is running
      service:
        name: jenkins
        state: started
        enabled: yes

    # -------------------------
    # Print initial admin password
    # -------------------------
    - name: Show Jenkins initial admin password
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password
      changed_when: false

    - debug:
        msg: "Jenkins initial admin password is {{ jenkins_password.stdout }}"
